Main:
  '♻️ 優先度低 - Low priority':
    - '♻️Status: Waiting [Low]'
  '☢️ 優先度高 - High priority':
    - '☢️Status: Waiting [High]'
  '🚧 作業中 - In Progress':
    - '🚧Status: In Progress'
  '✅ 完了済み - Done / Closed':
    - '✅Status: Done'
