name: 既存機能・コマンドの強化・改善提案・要望 - Improvement
description: 既にある機能やコマンドの強化や改善の提案・要望がある場合は、このテンプレートを使用してください。
labels: [ "♻improvement" ]
body:
  - type: markdown
    attributes:
      value: |
        jao Minecraft Server の Web サイト([`jaoafa/jaoweb`](https://github.com/jaoafa/jaoweb)) および Javajaotan2([`jaoafa/Javajaotan2`](https://github.com/jaoafa/Javajaotan2)) の不具合報告や新機能の提案は各リポジトリの Issue にてお願いします。どこに提出するべきかわからない場合は [jaoafa/jao-Minecraft-Server](https://github.com/jaoafa/jao-Minecraft-Server) へ。
        Issue の提出先が間違っていても、メンテナーが移動しますのでご安心ください。
  - type: textarea
    id: target
    attributes:
      label: 対象の機能・コマンド
      description: どの機能・コマンドに対するものかを示してください
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: 強化・改善の内容
      description: どのように強化・改善を行うかを示してください
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: 強化・改善を希望する理由
      description: 機能・コマンドに対してなぜその強化・改善を希望するのかを示してください
    validations:
      required: true
