name: Qodana Quality

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  qodana-quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt

      - name: Qodana Scan
        uses: JetBrains/qodana-action@v5.0.4
        timeout-minutes: 30
        with:
          upload-result: true
          args: "--linter,jetbrains/qodana-jvm-community,--fail-threshold,100"
          use-caches: false

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: results
          path: ${{ runner.temp }}/qodana/results

      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ runner.temp }}/qodana/results/report
          destination_dir: ./