name: Qodana Quality

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  qodana-quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt

      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2022.2.4
        timeout-minutes: 30
        with:
          upload-result: true
          args: "--linter,jetbrains/qodana-jvm-community,--fail-threshold,100"
          use-caches: false

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: results
          path: ${{ runner.temp }}/qodana/results

      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json

      - name: Upload Pages-artifact
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: actions/upload-pages-artifact@v1
        with:
          path: ${{ runner.temp }}/qodana/results/report

  deploy:
    runs-on: ubuntu-latest
    needs: qodana-quality
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1